import { StyleSheet } from 'react-native';
export const style = StyleSheet.create({
    container:{
        flex:1,
        justifyContent:'center',
    },
    image:{
        flex:5,
        resizeMode:'cover',
        
    },
    touch:{
        backgroundColor:"white",
        width:40,
        height:40,
        borderRadius:10,
        marginLeft:30,
        flexDirection:'column',
        textAlign:'center',
        marginTop:50,
        paddingLeft:12,
        paddingTop:3,
    },
    detailsContainer:{
        backgroundColor:'white',
        flex:5,
        marginTop:-20,
        borderTopLeftRadius:20,
        borderTopRightRadius:20,
    },
    nd:{
        flexDirection:'column',
        padding:20,
    },
    title:{
        fontWeight:'bold',
        fontSize:24,
        marginLeft:5,
        color:'black'
    },
    price:{
        fontWeight:'bold',
        fontSize:30,
        marginLeft:5,
        marginTop:10,
        marginBottom:10,
    },
    details:{
        marginLeft:5,
    },
    footer:{
        backgroundColor:"gray",
        flexDirection:'row',
        position: 'absolute',
        bottom:10,
        alignItems:'center',
        height:60,
        width:"100%",
        padding:5,
    },
    button1:{
        width:50,
        backgroundColor:'white',
        height:50,
        borderRadius:10,
        marginLeft:30,
        flexDirection:'column',
        alignItems:'center',
        paddingTop:4,
    },
    iconlike:{
        width:30,
        height:45,
    }
});